### ISSUE TITLE
Add integration tests for EquipmentHandler

### ISSUE THREAD

**Issue by ronaldbowers** [DAC-SSTAF/SSTAF#10]
EquipmentHandler does not have integration tests yet. Add one or more to help debug issues.

**Comment by canthurt** [comment]
So for testing, I have noticed these issues:

1.	SetGun does not work if the gun is not loaded (simple bug)
2.	Shoot gun does not work if the gun is not the current gun.  (same bug as #1)
3.	Reload with no magazines available ignores the reload failure.  Should throw an exception.

I’m thinking the best path forward would be to remove the reload at init, and add null checks around getMagazine().  I could see having multiple guns, setting the 2nd gun and using it exclusively.  This would end up with one less magazine, as it would be auto-loaded into the 1st gun that is not being used.

I’ll also add the same error tests to the analysis integration test to verify that the exceptions are being handled properly in the messages.
