### ISSUE TITLE
Build failure in mil.sstaf.analyzer

### ISSUE THREAD

**Issue by ronaldbowers** [DAC-SSTAF/SSTAF#3]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rbowers/Projects/SSTAF-tmp/SSTAF/src/build.gradle' line: 157

* What went wrong:
A problem occurred evaluating root project 'Unified SSTAF'.
> Could not find method implementation() for arguments [project ':framework:mil.sstaf.analyzer'] on object of type org.gradle.api.plugins.jvm.internal.DefaultJvmComponentDependencies.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 301ms

**Comment by canthurt** [comment]
This issue has been resolved along with issue #6.  See commit a135258.
